# Generated by Django 4.2.11 on 2024-03-17 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_image'),
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='books.books'),
        ),
    ]
