# Generated by Django 4.2.11 on 2024-03-17 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_authors_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='book',
        ),
    ]
